
[generation]
	# Structures listed here will have the relevant subbiome applied for if minecraft thinks that the block is inside the structure.
	structure_subbiomes = ["{\"struct\":\"pokecube:village\",\"subbiome\":\"village\"}", "{\"struct\":\"Village\",\"subbiome\":\"village\"}", "{\"struct\":\"minecraft:village\",\"subbiome\":\"village\"}", "{\"struct\":\"Monument\",\"subbiome\":\"monument\"}", "{\"struct\":\"minecraft:monument\",\"subbiome\":\"monument\"}"]
	# Does a blanket "plant material" check for cuttable and edible plants, rather than relying entirely on the block tags. [Default: true]
	autoPopulateLists = true

[blockentity]
	# sets teblacklist
	teblacklist = []
	# sets autoBlacklistErroredTEs
	autoBlacklistErroredTEs = true
	# sets blockblacklist
	blockblacklist = ["minecraft:bedrock"]

[biomes]
	# sets customBiomeMappings
	customBiomeMappings = []
	# sets resetAllTerrain
	resetAllTerrain = false

[client]
	# sets asyncModelLoads
	asyncModelLoads = true

[explosions]
	# sets minBlastEffect
	minBlastEffect = 0.25
	# sets affectAir
	affectAir = true
	# sets generateCache
	generateCache = true
	# sets maxMsPerTick
	maxMsPerTick = 25
	# sets explosionRadius
	explosionRadius = 127

[misc]
	# sets debug
	debug = true
	# sets supress_warns
	supress_warns = false

